name: Get CIDR List

on:
  schedule:
    # Запуск каждый день в 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch:  # Возможность ручного запуска

jobs:
  update-cidr:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Download and update CIDR file
        run: |
          mkdir -p src/IPs
          curl -L -o src/IPs/CIDR-ru.txt https://raw.githubusercontent.com/hydraponique/roscomvpn-geoip/refs/heads/master/release/text/direct.txt
      
      - name: Check if file has changed
        id: check
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
            echo "Files changed:"
            git status --porcelain
          else
            echo "changes=false" >> $GITHUB_OUTPUT
            echo "No changes"
          fi
      
      - name: Commit and push changes
        if: steps.check.outputs.changes == 'true'
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add src/IPs/CIDR-ru.txt
          git commit -m "chore: update CIDR list from roscomvpn-geoip"
          git push